# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lM-XUZ4bUwhal_V48sICxBahC61LnmHm
"""

# Importing the necessary liblaries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# Reading the CSV file with the correct delimiter
df = pd.read_csv('Marketing-bank.csv', delimiter=';')

# Count plot using Seaborn
sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.countplot(x="Campaign_Type", hue="Response", data=df, palette=sns.color_palette())

# Setting the title and X-Y axis
plt.title('Responses Count by Campaign Type')
plt.xlabel('Campaign Type')
plt.ylabel('Count')

# Showing the plot
plt.show()